import javax.swing.*;
import java.awt.*;

public class CovidCalculator {

    public static void main(String[] args) {
        JFrame mFrame = new JFrame();
        mFrame.setVisible(true);
        mFrame.setSize(500, 600);
        mFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JPanel mWindow = new JPanel(new BorderLayout());
        mFrame.getContentPane().add(mWindow, BorderLayout.BEFORE_FIRST_LINE);

        // The upperHalf of 2 rows panel which contains the date and ini number panels + Ep slider panel
        JPanel upperHalf = new JPanel(new GridLayout(2, 1));
        upperHalf.setPreferredSize(new Dimension(470, 200));

        // The choose date and initial number of cases gridpanel of 2 rows;Each row has 1 flowPanel(1st contains the
        // DateChoosers and second the selection of Nr of cases);
        JPanel datesCases = new JPanel(new GridLayout(2, 1));

        JPanel fromAndToDate = new JPanel(new FlowLayout(FlowLayout.LEADING, 200, 0));
        JLabel from = new JLabel("From");
        JLabel to = new JLabel("From");
        fromAndToDate.add(from);
        fromAndToDate.add(to);


        JPanel numIni = new JPanel(new FlowLayout());
        JLabel nO = new JLabel("No cases");
        JTextArea nOText = new JTextArea();
        numIni.add(nO);
        numIni.add(nOText);

        datesCases.add(fromAndToDate);
        datesCases.add(numIni);

        upperHalf.add(datesCases);

        // The ep gridpanel of 2 rows,first is for label + text,second is for slider;
        JPanel ep = new JPanel(new GridLayout(2, 1));

        JPanel epLab = new JPanel(new FlowLayout());
        JPanel epSlider = new JPanel();
        JSlider epSlide = new JSlider();

        epSlider.add(epSlide);


        ep.add(epLab);
        ep.add(epSlider);

        upperHalf.add(ep);

        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.HORIZONTAL;
        c.anchor = GridBagConstraints.WEST;
        mWindow.add(upperHalf);


        // Lower half borderPanel contains stats on left and graph center
        JPanel lowerH = new JPanel(new BorderLayout());

        JPanel stats = new JPanel(new FlowLayout());

        //jFREE CHART

        lowerH.add(stats, BorderLayout.WEST);

        mWindow.add(lowerH);


// Jlabelfrom;
// Jlabelto;
// Jdatepickerfrom;
// JdatePickerto;

// JlabelNo;
// JTextNo;

// JlabelPe;
// Jtext Pe;
// JsliderPe;

// JlabelDeaths;
// Jlabelcases;
// Jlabelsymptom;
// Jlabel%casi;
// JlabelNonInfetti;

// Jgraph;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
